#!/bin/bash

# Check if service is running.
if [ $(pgrep mysql | wc -l) -gt 0 ];
then
  service mysql stop
fi

# Force the MySQL user on these folders, if applicable.
if [ -d /var/lib/mysql ]; then
  chown -R mysql:mysql /var/lib/mysql
fi

if [ -d /var/run/mysqld ]; then
  chown -R mysql:mysql /var/run/mysqld
fi

service mysql start

# Prevent an unnecessary error if the container is restarted.
mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS drupal;"

# Start the Drupal service.
service drupal start

# Clear all cache.
drush cc all

# Execute the testing group.
drupal-simpletest "${test:- }"
