#!/bin/bash

SCRIPTNAME="${0##*/}"
MODULES_ENABLE="$2"

case "$1" in
  start)
    drush cutie --yes --root=/var/www/html --server=:80 --profile=minimal --enable=simpletest,$MODULES_ENABLE --db-url=mysql://root:root@localhost:3306/drupal
    ;;

  *)
    echo "Usage: $SCRIPTNAME start" >&2
    exit 3
    ;;
esac

exit 0
