#!/bin/bash

SCRIPTNAME="${0##*/}"

case "$1" in
  start)
    drush cutie ${modules:- } --yes --root=/var/www/html --no-browser --no-server --profile=minimal --enable=${enable:-simpletest} --db-url=mysql://root:root@localhost:3306/drupal
    ;;

  *)
    echo "Usage: $SCRIPTNAME start" >&2
    exit 3
    ;;
esac

exit 0
