#!/bin/bash

ORIGIN=$(pwd)

cd /var/www/html

php scripts/run-tests.sh --color --verbose --url http://localhost --xml /var/www/html/results "$1"

# Grab the results of simpletest since `cd` will always return 0.
RESULTS=$?

cd $ORIGIN

# Exit with the same code that came with simpletest.
exit $RESULTS
